/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fidartech.frame;

import com.fidartech.setting.SettingHandler;
import java.awt.AWTException;
import java.awt.Color;
import java.awt.Image;
import java.awt.SystemTray;
import java.awt.TrayIcon;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author alirezakhtm
 */
public class MainFrame extends javax.swing.JFrame {

    private boolean felagSMSConsumerExist = false;
    private boolean felagDeliveryConsumerExist = false;
    private boolean felagSMSSender = false;
    private boolean felagSubAndUnsub = false;
    private SettingFrame settingFrame = new SettingFrame();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        // check libs that are exits
        try{
            File[] allJarFile = (new File("lib")).listFiles(new FileFilter() {
                @Override
                public boolean accept(File pathname) {
                    return pathname.getName().endsWith(".jar");
                }
            });
            for(File f : allJarFile){
                if(f.getName().equals("ConsumerSMSParsing.jar")){
                   felagSMSConsumerExist = true; 
                   lblLicenceSMSConcumer.setText("Licence found.");
                   lblLicenceSMSConcumer.setForeground(Color.blue);
                }
                if(f.getName().equals("ConsumerDeliveryParsing.jar")){
                    felagDeliveryConsumerExist = true;
                    lblLicenceDeliveryConsumer.setText("Licence found.");
                    lblLicenceDeliveryConsumer.setForeground(Color.blue);
                }
                if(f.getName().equals("ConsumerSMSSender.jar")){
                    felagSMSSender = true;
                    lblLicenceSMSSender.setText("Licence found.");
                    lblLicenceSMSSender.setForeground(Color.blue);
                }
                if(f.getName().equals("ConsumerAddDelParsing.jar")){
                    felagSubAndUnsub = true;
                    lblLicenceSubUnSubUser.setText("Licence found.");
                    lblLicenceSubUnSubUser.setForeground(Color.blue);
                }
            }
            btnStartSMSParsing.setEnabled(felagSMSConsumerExist);
            btnStartDeliveryParsing.setEnabled(felagDeliveryConsumerExist);
            btnStartSMSSender.setEnabled(felagSMSSender);
            btnStartSubAndUnsub.setEnabled(felagSubAndUnsub);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        // set icon for popup menu
        InputStream inputStream = MainFrame.class.getResourceAsStream("/com/fidartech/frame/icon/server.png");
        try {
            BufferedImage bi = ImageIO.read(inputStream);
            ImageIcon icon = new ImageIcon(bi);
            Image img = bi.getScaledInstance(16, 16, 16);
            SystemTray tray = SystemTray.getSystemTray();
            TrayIcon trayIcon = new TrayIcon(img, "Consumers", popupMenuGeneral);
            tray.add(trayIcon);
        } catch (IOException | AWTException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenuGeneral = new java.awt.PopupMenu();
        mitm_showFrame = new java.awt.MenuItem();
        mitm_exitFrame = new java.awt.MenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblLicenceDeliveryConsumer = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnStartDeliveryParsing = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblLicenceSMSConcumer = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnStartSMSParsing = new javax.swing.JButton();
        btnConfigDatabase = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblLicenceSubUnSubUser = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnStartSubAndUnsub = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblLicenceSMSSender = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnStartSMSSender = new javax.swing.JButton();

        popupMenuGeneral.setLabel("Consumer");

        mitm_showFrame.setLabel("Show");
        mitm_showFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitm_showFrameActionPerformed(evt);
            }
        });
        popupMenuGeneral.add(mitm_showFrame);

        mitm_exitFrame.setLabel("Exit");
        mitm_exitFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitm_exitFrameActionPerformed(evt);
            }
        });
        popupMenuGeneral.add(mitm_exitFrame);

        setTitle("Consumer Manager");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fidartech/frame/icon/if_ledlightblue_1785.png"))); // NOI18N
        jLabel2.setText("Delivery's Consumer");

        lblLicenceDeliveryConsumer.setForeground(new java.awt.Color(204, 0, 0));
        lblLicenceDeliveryConsumer.setText("You dont have licence of Delivery's consumer !");

        btnStartDeliveryParsing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fidartech/frame/icon/play-button-sing.png"))); // NOI18N
        btnStartDeliveryParsing.setEnabled(false);
        btnStartDeliveryParsing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartDeliveryParsingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStartDeliveryParsing)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStartDeliveryParsing)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLicenceDeliveryConsumer)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(lblLicenceDeliveryConsumer)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fidartech/frame/icon/if_ledlightblue_1785.png"))); // NOI18N
        jLabel1.setText("SMS's Consumer");

        lblLicenceSMSConcumer.setForeground(new java.awt.Color(204, 0, 0));
        lblLicenceSMSConcumer.setText("You dont have licence of SMS's consumer !");

        btnStartSMSParsing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fidartech/frame/icon/play-button-sing.png"))); // NOI18N
        btnStartSMSParsing.setEnabled(false);
        btnStartSMSParsing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartSMSParsingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStartSMSParsing)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStartSMSParsing)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLicenceSMSConcumer)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(lblLicenceSMSConcumer, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        btnConfigDatabase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fidartech/frame/icon/database.png"))); // NOI18N
        btnConfigDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigDatabaseActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fidartech/frame/icon/if_ledlightblue_1785.png"))); // NOI18N
        jLabel3.setText("Sub and Unsub User 's Consumer");

        lblLicenceSubUnSubUser.setForeground(new java.awt.Color(204, 0, 0));
        lblLicenceSubUnSubUser.setText("You dont have licence of Delivery's consumer !");

        btnStartSubAndUnsub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fidartech/frame/icon/play-button-sing.png"))); // NOI18N
        btnStartSubAndUnsub.setEnabled(false);
        btnStartSubAndUnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartSubAndUnsubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStartSubAndUnsub)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStartSubAndUnsub)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLicenceSubUnSubUser)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(lblLicenceSubUnSubUser)))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fidartech/frame/icon/if_ledlightblue_1785.png"))); // NOI18N
        jLabel4.setText("SMS Sender's Consumer");

        lblLicenceSMSSender.setForeground(new java.awt.Color(204, 0, 0));
        lblLicenceSMSSender.setText("You dont have licence of Delivery's consumer !");

        btnStartSMSSender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fidartech/frame/icon/play-button-sing.png"))); // NOI18N
        btnStartSMSSender.setEnabled(false);
        btnStartSMSSender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartSMSSenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStartSMSSender)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStartSMSSender)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLicenceSMSSender)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(lblLicenceSMSSender)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfigDatabase))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnConfigDatabase)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartSMSParsingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartSMSParsingActionPerformed
        btnConfigDatabase.setEnabled(false);
        SettingHandler settingHandler = new SettingHandler();
        consumersmsparsing.ConsumerSMSParsing.main(new String[]{settingHandler.getDelay()});
        btnStartSMSParsing.setEnabled(false);
        // create InputStream from image file that saved on resource
        InputStream inputStream = MainFrame.class.getResourceAsStream("/com/fidartech/frame/icon/if_ledorange_1787.png");
        try {
            // create buffer for reading image
            BufferedImage bufferedImage = ImageIO.read(inputStream);
            // create ImageIcon from BufferedImage
            ImageIcon icon = new ImageIcon(bufferedImage);
            // set image Icon to lable
            jLabel1.setIcon(icon);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnStartSMSParsingActionPerformed

    private void mitm_showFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitm_showFrameActionPerformed
        this.setVisible(true);
    }//GEN-LAST:event_mitm_showFrameActionPerformed

    private void mitm_exitFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitm_exitFrameActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mitm_exitFrameActionPerformed

    private void btnStartDeliveryParsingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartDeliveryParsingActionPerformed
        btnConfigDatabase.setEnabled(false);
        SettingHandler settingHandler = new SettingHandler();
        consumerdeliveryparsing.ConsumerDeliveryParsing.main(new String[]{settingHandler.getDelay()});
        btnStartDeliveryParsing.setEnabled(false);
        // create InputStream from image file that saved on resource
        InputStream inputStream = MainFrame.class.getResourceAsStream("/com/fidartech/frame/icon/if_ledorange_1787.png");
        try{
            // create buffer for reading image
            BufferedImage bufferedImage = ImageIO.read(inputStream);
            // create ImageIcon from BufferedImage
            ImageIcon icon = new ImageIcon(bufferedImage);
            // set image Icon to lable
            jLabel2.setIcon(icon);
        }catch(IOException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnStartDeliveryParsingActionPerformed

    private void btnConfigDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigDatabaseActionPerformed
        settingFrame.setVisible(true);
    }//GEN-LAST:event_btnConfigDatabaseActionPerformed

    private void btnStartSubAndUnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartSubAndUnsubActionPerformed
        btnConfigDatabase.setEnabled(false);
        SettingHandler settingHandler = new SettingHandler();
        consumeradddelparsing.ConsumerAddDelParsing.main(new String[]{settingHandler.getDelay()});
        btnStartSubAndUnsub.setEnabled(false);
        // create InputStream from image file that saved on resource
        InputStream inputStream = MainFrame.class.getResourceAsStream("/com/fidartech/frame/icon/if_ledorange_1787.png");
        try{
            // create buffer for reading image
            BufferedImage bufferedImage = ImageIO.read(inputStream);
            // create ImageIcon from BufferedImage
            ImageIcon icon = new ImageIcon(bufferedImage);
            // set image Icon to lable
            jLabel3.setIcon(icon);
        }catch(IOException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnStartSubAndUnsubActionPerformed

    private void btnStartSMSSenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartSMSSenderActionPerformed
        btnConfigDatabase.setEnabled(false);
        SettingHandler settingHandler = new SettingHandler();
        consumersmssender.ConsumerSMSSender.main(new String[]{settingHandler.getDelay()});
        btnStartSMSSender.setEnabled(false);
        // create InputStream from image file that saved on resource
        InputStream inputStream = MainFrame.class.getResourceAsStream("/com/fidartech/frame/icon/if_ledorange_1787.png");
        try{
            // create buffer for reading image
            BufferedImage bufferedImage = ImageIO.read(inputStream);
            // create ImageIcon from BufferedImage
            ImageIcon icon = new ImageIcon(bufferedImage);
            // set image Icon to lable
            jLabel4.setIcon(icon);
        }catch(IOException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnStartSMSSenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfigDatabase;
    private javax.swing.JButton btnStartDeliveryParsing;
    private javax.swing.JButton btnStartSMSParsing;
    private javax.swing.JButton btnStartSMSSender;
    private javax.swing.JButton btnStartSubAndUnsub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblLicenceDeliveryConsumer;
    private javax.swing.JLabel lblLicenceSMSConcumer;
    private javax.swing.JLabel lblLicenceSMSSender;
    private javax.swing.JLabel lblLicenceSubUnSubUser;
    private java.awt.MenuItem mitm_exitFrame;
    private java.awt.MenuItem mitm_showFrame;
    private java.awt.PopupMenu popupMenuGeneral;
    // End of variables declaration//GEN-END:variables
}
