
package com.digidaroo.smsWS;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "sendSMSWebService", targetNamespace = "http://sendsms.digidaroo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendSMSWebService {


    /**
     * 
     * @param message
     * @param msisdn
     * @return
     *     returns java.lang.String
     * @throws PolicyExceptionException
     * @throws ServiceExceptionException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendSMS", targetNamespace = "http://sendsms.digidaroo.com/", className = "com.digidaroo.smsWS.SendSMS")
    @ResponseWrapper(localName = "sendSMSResponse", targetNamespace = "http://sendsms.digidaroo.com/", className = "com.digidaroo.smsWS.SendSMSResponse")
    @Action(input = "http://sendsms.digidaroo.com/sendSMSWebService/sendSMSRequest", output = "http://sendsms.digidaroo.com/sendSMSWebService/sendSMSResponse", fault = {
        @FaultAction(className = PolicyExceptionException.class, value = "http://sendsms.digidaroo.com/sendSMSWebService/sendSMS/Fault/PolicyException_Exception"),
        @FaultAction(className = ServiceExceptionException.class, value = "http://sendsms.digidaroo.com/sendSMSWebService/sendSMS/Fault/ServiceException_Exception")
    })
    public String sendSMS(
        @WebParam(name = "message", targetNamespace = "")
        String message,
        @WebParam(name = "msisdn", targetNamespace = "")
        String msisdn)
        throws PolicyExceptionException, ServiceExceptionException
    ;

}
