
package com.digidaroo.smsWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "sendSMSWebService", targetNamespace = "http://sendsms.digidaroo.com/", wsdlLocation = "http://localhost:8080/DigidarooWS/sendSMSWebService?wsdl")
public class SendSMSWebService_Service
    extends Service
{

    private final static URL SENDSMSWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException SENDSMSWEBSERVICE_EXCEPTION;
    private final static QName SENDSMSWEBSERVICE_QNAME = new QName("http://sendsms.digidaroo.com/", "sendSMSWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/DigidarooWS/sendSMSWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENDSMSWEBSERVICE_WSDL_LOCATION = url;
        SENDSMSWEBSERVICE_EXCEPTION = e;
    }

    public SendSMSWebService_Service() {
        super(__getWsdlLocation(), SENDSMSWEBSERVICE_QNAME);
    }

    public SendSMSWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENDSMSWEBSERVICE_QNAME, features);
    }

    public SendSMSWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SENDSMSWEBSERVICE_QNAME);
    }

    public SendSMSWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENDSMSWEBSERVICE_QNAME, features);
    }

    public SendSMSWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendSMSWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SendSMSWebService
     */
    @WebEndpoint(name = "sendSMSWebServicePort")
    public SendSMSWebService getSendSMSWebServicePort() {
        return super.getPort(new QName("http://sendsms.digidaroo.com/", "sendSMSWebServicePort"), SendSMSWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendSMSWebService
     */
    @WebEndpoint(name = "sendSMSWebServicePort")
    public SendSMSWebService getSendSMSWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sendsms.digidaroo.com/", "sendSMSWebServicePort"), SendSMSWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENDSMSWEBSERVICE_EXCEPTION!= null) {
            throw SENDSMSWEBSERVICE_EXCEPTION;
        }
        return SENDSMSWEBSERVICE_WSDL_LOCATION;
    }

}
